# Generated by Django 4.2.7 on 2023-12-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Volunteer', '0003_volunteerevent_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='organization_id',
            new_name='company_id',
        ),
        migrations.RenameField(
            model_name='participation',
            old_name='event_id',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='participation',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='organization',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='volunteerevent',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='participation',
            name='attendance',
        ),
        migrations.AddField(
            model_name='organization',
            name='company_number',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
