# Generated by Django 4.2.7 on 2023-12-05 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Volunteer', '0004_rename_organization_id_organization_company_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerevent',
            name='mbti_type',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='contact',
            field=models.CharField(max_length=25),
        ),
    ]
