# Generated by Django 4.2.7 on 2023-12-06 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Volunteer', '0005_volunteerevent_mbti_type_alter_user_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participation',
            old_name='event',
            new_name='event_id',
        ),
        migrations.RenameField(
            model_name='participation',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='volunteerevent',
            old_name='user',
            new_name='user_id',
        ),
    ]
